from datetime import datetime
from pathlib import Path
import random
from uuid import uuid4

import pandas as pd
from flask import Flask, render_template, request, send_file
from werkzeug.utils import secure_filename

BASE_DIR = Path(__file__).resolve().parent
UPLOAD_DIR = BASE_DIR / "uploads"
OUTPUT_DIR = BASE_DIR / "outputs"
RESULTS_DIR = BASE_DIR / "results"
ALLOWED_EXTENSIONS = {"csv"}

UPLOAD_DIR.mkdir(exist_ok=True)
OUTPUT_DIR.mkdir(exist_ok=True)
RESULTS_DIR.mkdir(exist_ok=True)

app = Flask(__name__)

DEFAULT_COLLECTION_INTENTS: list[dict[str, str]] = [
    {
        "intent": "MAKE_PAYMENT",
        "description": "Customer wants to make a payment immediately on the past-due balance.",
    },
    {
        "intent": "PAYMENT_PLAN",
        "description": "Customer wants to set up an installment or hardship payment arrangement.",
    },
    {
        "intent": "DISPUTE_BALANCE",
        "description": "Customer disputes the amount due, fees, or account ownership.",
    },
    {
        "intent": "PROMISE_TO_PAY",
        "description": "Customer commits to paying by a specific future date.",
    },
    {
        "intent": "REQUEST_EXTENSION",
        "description": "Customer asks for extra time or a due-date extension.",
    },
    {
        "intent": "FALLBACK",
        "description": "Out-of-scope request not supported by the collections chatbot.",
    },
]

COLLECTION_PRODUCTS = [
    "credit card",
    "personal loan",
    "auto loan",
    "mortgage",
    "student loan",
    "business loan",
]

OOS_REQUESTS = [
    "book a flight to New York",
    "recommend a local plumber",
    "plan a wedding timeline",
    "suggest a workout routine",
    "find pet grooming services nearby",
    "share this week's weather forecast",
]


def is_allowed_file(filename: str) -> bool:
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


def merge_csv_files(file_paths: list[Path], uploaded_info: list[dict]) -> tuple[Path, Path]:
    merged_data = []
    for csv_path in file_paths:
        df = pd.read_csv(csv_path, index_col=None, header=0)
        merged_data.append(df)

    if not merged_data:
        raise ValueError("No valid CSV files provided.")

    result = pd.concat(merged_data, axis=0, ignore_index=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_dir = RESULTS_DIR / timestamp
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Save Merged CSV
    output_name = f"merged_{uuid4().hex}.csv"
    output_path = output_dir / output_name
    result.to_csv(output_path, index=False)
    
    # Generate Text Report
    report_content = [
        f"CSV MERGE REPORT - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "=" * 50,
        "\nUPLOADED FILES:",
    ]
    
    for info in uploaded_info:
        report_content.append(f"- {info['name']}")
        report_content.append(f"  Rows: {info['rows']}")
        report_content.append(f"  Headers: {', '.join(info['headers'])}")
        report_content.append("-" * 30)
        
    report_content.extend([
        "\nMERGED RESULT:",
        f"- Total Rows: {len(result)}",
        f"- Total Columns: {len(result.columns)}",
        f"- Headers: {', '.join(result.columns)}",
        "\n" + "=" * 50,
        "Generated by CSV Workspace"
    ])
    
    report_path = output_dir / "report.txt"
    report_path.write_text("\n".join(report_content))
    
    return output_path, report_path


def build_generated_row(index: int, template: str, columns: list[str]) -> dict[str, str | int | float]:
    first_names = ["Ava", "Noah", "Mia", "Liam", "Ethan", "Zoe", "Ella", "Lucas", "Mason", "Aria"]
    last_names = ["Carter", "Smith", "Lopez", "Johnson", "Lee", "Brown", "Patel", "Wilson", "Taylor", "White"]
    departments = ["Sales", "Support", "Finance", "Engineering", "HR", "Marketing"]
    countries = ["USA", "Canada", "UK", "Germany", "India", "Kenya", "Brazil", "Japan"]
    products = ["Laptop", "Phone", "Tablet", "Headset", "Monitor", "Keyboard"]

    row: dict[str, str | int | float] = {}
    for column in columns:
        col_key = column.strip().lower()

        if col_key in {"id", "record_id"}:
            value: str | int | float = index + 1
        elif col_key in {"name", "full_name"}:
            value = f"{random.choice(first_names)} {random.choice(last_names)}"
        elif col_key == "first_name":
            value = random.choice(first_names)
        elif col_key == "last_name":
            value = random.choice(last_names)
        elif col_key == "email":
            value = f"user{index + 1}@example.com"
        elif col_key in {"age", "years"}:
            value = random.randint(18, 65)
        elif col_key in {"country", "region"}:
            value = random.choice(countries)
        elif col_key == "department":
            value = random.choice(departments)
        elif col_key in {"salary", "amount", "price"}:
            value = round(random.uniform(120.0, 9500.0), 2)
        elif col_key in {"quantity", "count"}:
            value = random.randint(1, 120)
        elif col_key in {"product", "product_name"}:
            value = random.choice(products)
        elif col_key in {"status", "state"}:
            value = random.choice(["New", "In Progress", "Closed", "Pending"])
        elif col_key in {"date", "created_at"}:
            value = f"2026-02-{(index % 28) + 1:02d}"
        elif template == "sales":
            if col_key == "customer":
                value = f"{random.choice(first_names)} {random.choice(last_names)}"
            elif col_key == "order_id":
                value = f"ORD-{10000 + index}"
            elif col_key == "city":
                value = random.choice(["Seattle", "Austin", "New York", "Chicago", "Denver"])
            else:
                value = f"{column}_{index + 1}"
        elif template == "contacts":
            if col_key == "phone":
                value = f"+1-555-{random.randint(100, 999)}-{random.randint(1000, 9999)}"
            elif col_key == "company":
                value = random.choice(["Apex Labs", "Northwind", "Sunline", "Peak Data", "Bluecore"])
            else:
                value = f"{column}_{index + 1}"
        else:
            value = f"{column}_{index + 1}"

        row[column] = value

    return row


def parse_label_list(raw_value: str, fallback: list[str]) -> list[str]:
    labels = [item.strip() for item in raw_value.split(",") if item.strip()]
    return labels or fallback


def parse_probability_list(raw_value: str, expected_len: int) -> list[float]:
    values = [item.strip() for item in raw_value.split(",") if item.strip()]
    if len(values) != expected_len:
        raise ValueError(f"Expected {expected_len} probability values, got {len(values)}.")
    try:
        probs = [float(value) for value in values]
    except ValueError as exc:
        raise ValueError("Probability values must be numeric.") from exc

    if any(prob < 0 for prob in probs):
        raise ValueError("Probabilities must be non-negative.")
    total = sum(probs)
    if total <= 0:
        raise ValueError("Probability sum must be greater than 0.")
    return [prob / total for prob in probs]


def parse_custom_intents(raw_value: str) -> list[dict[str, str]]:
    """
    Format:
      INTENT|Description
      INTENT_2|Description
    """
    intents: list[dict[str, str]] = []
    for line in raw_value.splitlines():
        line = line.strip()
        if not line:
            continue
        if "|" not in line:
            raise ValueError("Custom intents must use `INTENT|Description` per line.")
        intent, description = [part.strip() for part in line.split("|", 1)]
        if not intent or not description:
            raise ValueError("Custom intents require both intent and description.")
        intents.append({"intent": intent.upper(), "description": description})

    if not intents:
        return DEFAULT_COLLECTION_INTENTS.copy()

    if "FALLBACK" not in {row["intent"] for row in intents}:
        intents.append(
            {
                "intent": "FALLBACK",
                "description": "Out-of-scope request not supported by the collections chatbot.",
            }
        )
    return intents


def apply_speech_style(text: str, speech_type: str) -> str:
    speech = speech_type.lower().strip()
    if speech == "professional":
        replacements = {
            "can't": "cannot",
            "won't": "will not",
            "I'd": "I would",
            "I'm": "I am",
        }
        for src, dst in replacements.items():
            text = text.replace(src, dst)
        return text

    if speech == "slang":
        replacements = {
            "please": "pls",
            "because": "cuz",
            "about": "abt",
            "with": "w/",
            "to": "2",
        }
        words = text.split(" ")
        transformed = [replacements.get(word.lower(), word) for word in words]
        return " ".join(transformed)

    if speech == "typos":
        text = text.replace("th", "t").replace("ing", "in")
        text = text.replace("you", "u").replace("please", "pls")
        return text

    return text


def build_scenario_for_intent(intent: str, description: str, temperature: float) -> str:
    product = random.choice(COLLECTION_PRODUCTS)
    days_past_due = random.choice([15, 30, 45, 60, 75])
    hardship = random.choice(
        [
            "lost overtime hours at work",
            "had an unexpected medical bill",
            "is juggling childcare expenses",
            "is recovering from a temporary income drop",
            "experienced a recent car repair emergency",
        ]
    )

    if intent == "MAKE_PAYMENT":
        scenario = (
            f"The bank reaches out about a {days_past_due}-day past-due {product}. "
            f"The customer says they can pay today if they can confirm the total due and payment channels."
        )
    elif intent == "PAYMENT_PLAN":
        scenario = (
            f"After an outreach about a delinquent {product}, the customer explains they {hardship} "
            "and asks for a structured multi-month payment plan."
        )
    elif intent == "DISPUTE_BALANCE":
        scenario = (
            f"The customer receives a collections message for a {product} and argues the balance includes fees "
            "they do not recognize, asking for a breakdown and dispute process."
        )
    elif intent == "PROMISE_TO_PAY":
        promised_day = random.choice(["Friday", "next Tuesday", "the 15th", "end of month"])
        scenario = (
            f"During collections outreach on a past-due {product}, the customer cannot pay right now "
            f"but commits to making payment by {promised_day}."
        )
    elif intent == "REQUEST_EXTENSION":
        scenario = (
            f"The customer acknowledges the delinquent {product} but asks for a short due-date extension "
            "until their next paycheck arrives."
        )
    else:
        # Fallback / OOS intent
        request = random.choice(OOS_REQUESTS)
        scenario = (
            f"The bank contacts a customer regarding a past-due {product}. "
            f"Instead of discussing collections, the customer asks the chatbot to {request}."
        )

    if temperature > 0.9:
        flair = random.choice(
            [
                " The customer is stressed and asks multiple follow-up questions.",
                " The conversation starts politely but quickly becomes urgent.",
                " The customer references prior failed attempts to resolve the issue.",
            ]
        )
        scenario += flair
    return f"{scenario} Intent definition: {description}"


def generate_collection_scenarios(
    intents: list[dict[str, str]],
    num_scenarios: int,
    temperature: float,
) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    in_scope_intents = [row["intent"] for row in intents if row["intent"] != "FALLBACK"]

    for row in intents:
        intent = row["intent"]
        description = row["description"]
        for _ in range(num_scenarios):
            if intent == "FALLBACK":
                scenario = build_scenario_for_intent(intent, description, temperature)
                if in_scope_intents:
                    scenario += f" Avoid classifying as: {', '.join(in_scope_intents)}."
            else:
                scenario = build_scenario_for_intent(intent, description, temperature)
            rows.append({"intent": intent, "scenario": scenario})
    return rows


def generate_conversation_text(intent: str, scenario: str, sentiment: str, user_speech_type: str) -> str:
    opener = random.choice(
        [
            "Bot: Hello, this is the collections team from your bank regarding a past-due balance.",
            "Bot: Hi, I am reaching out from the bank collections desk about your overdue account.",
            "Bot: Good day, this is an automated collections outreach concerning your delinquent balance.",
        ]
    )

    user_lines: dict[str, str] = {
        "MAKE_PAYMENT": "User: I can pay today. Please tell me the exact amount and quickest payment option.",
        "PAYMENT_PLAN": "User: I cannot pay the full amount now. Can we set up a payment plan?",
        "DISPUTE_BALANCE": "User: I do not think this balance is correct. I need a fee breakdown.",
        "PROMISE_TO_PAY": "User: I cannot pay now, but I can pay by next week.",
        "REQUEST_EXTENSION": "User: I need a short extension until my next paycheck.",
        "FALLBACK": "User: Can you help me with something unrelated instead?",
    }

    bot_resolution: dict[str, str] = {
        "MAKE_PAYMENT": "Bot: I can guide you through one-time payment steps and confirm completion.",
        "PAYMENT_PLAN": "Bot: I can review eligible installment options and hardship programs.",
        "DISPUTE_BALANCE": "Bot: I can open a balance dispute and share documentation requirements.",
        "PROMISE_TO_PAY": "Bot: I can record your promise-to-pay date and send a reminder.",
        "REQUEST_EXTENSION": "Bot: I can check extension eligibility and note your request.",
        "FALLBACK": "Bot: I can only help with account collections topics. I can route you to supported options.",
    }

    sentiment_tone = {
        "angry": "User: This is frustrating and I need this resolved immediately.",
        "confused": "User: I am confused about what happens next and what my options are.",
        "neutral": "User: Understood. Please explain the next steps.",
    }.get(sentiment.lower(), "User: Okay, please continue.")

    first_user = apply_speech_style(user_lines.get(intent, user_lines["FALLBACK"]), user_speech_type)
    second_user = apply_speech_style(sentiment_tone, user_speech_type)

    dialogue = [
        opener,
        first_user,
        bot_resolution.get(intent, bot_resolution["FALLBACK"]),
        second_user,
        "Bot: " + scenario,
    ]
    return "\n".join(dialogue)


def generate_collections_csv_file(
    *,
    num_scenarios: int,
    num_variants: int,
    temperature: float,
    sentiments: list[str],
    sentiment_probs: list[float],
    user_speech: list[str],
    user_speech_probs: list[float],
    custom_intents: str,
) -> Path:
    intents = parse_custom_intents(custom_intents)
    scenarios = generate_collection_scenarios(
        intents=intents,
        num_scenarios=num_scenarios,
        temperature=temperature,
    )

    rows: list[dict[str, str]] = []
    for scenario_row in scenarios:
        for _ in range(num_variants):
            sentiment = random.choices(sentiments, weights=sentiment_probs, k=1)[0]
            speech = random.choices(user_speech, weights=user_speech_probs, k=1)[0]
            rows.append(
                {
                    "intent": scenario_row["intent"],
                    "scenario": scenario_row["scenario"],
                    "conversation_text": generate_conversation_text(
                        scenario_row["intent"],
                        scenario_row["scenario"],
                        sentiment,
                        speech,
                    ),
                    "sentiment": sentiment,
                    "user_speech_type": speech,
                }
            )

    output_name = f"generated_collections_{uuid4().hex}.csv"
    output_path = OUTPUT_DIR / output_name
    pd.DataFrame(rows).to_csv(output_path, index=False)
    return output_path


def generate_csv_file(template: str, rows: int, custom_columns: str) -> Path:
    template_columns = {
        "contacts": ["id", "full_name", "email", "phone", "company", "country"],
        "sales": ["order_id", "customer", "product", "quantity", "price", "status", "date"],
        "employees": ["id", "first_name", "last_name", "department", "salary", "country", "email"],
    }

    if custom_columns.strip():
        columns = [col.strip() for col in custom_columns.split(",") if col.strip()]
    else:
        columns = template_columns.get(template, template_columns["contacts"])

    if not columns:
        raise ValueError("Please provide at least one valid column.")

    rows = max(1, min(rows, 10000))
    generated_rows = [build_generated_row(i, template, columns) for i in range(rows)]
    result = pd.DataFrame(generated_rows, columns=columns)

    output_name = f"generated_{template}_{uuid4().hex}.csv"
    output_path = OUTPUT_DIR / output_name
    result.to_csv(output_path, index=False)
    return output_path


def build_results_context(data_file: Path, source_label: str) -> dict:
    result_df = pd.read_csv(data_file)
    preview_rows = result_df.head(12).to_dict(orient="records")
    preview_headers = result_df.columns.tolist()

    chart_labels: list[str] = []
    chart_values: list[int] = []
    if not result_df.empty and preview_headers:
        first_column = result_df.iloc[:, 0].astype(str)
        value_counts = first_column.value_counts(dropna=False).head(10)
        chart_labels = value_counts.index.tolist()
        chart_values = value_counts.values.tolist()

    return {
        "merged_filename": str(data_file.relative_to(BASE_DIR)),
        "total_rows": len(result_df),
        "total_columns": len(preview_headers),
        "headers": preview_headers,
        "preview_rows": preview_rows,
        "chart_labels": chart_labels,
        "chart_values": chart_values,
        "source_label": source_label,
    }


@app.route("/", methods=["GET", "POST"])
def index():
    if request.method == "GET":
        return render_template("index.html", active_menu="upload")

    action = request.form.get("action", "upload").strip().lower()
    active_menu = "generate" if action == "generate" else "upload"

    if action == "generate":
        template = request.form.get("template", "contacts").strip().lower()
        rows_input = request.form.get("rows", "100").strip()
        custom_columns = request.form.get("columns", "").strip()

        if template == "collections_synthetic":
            try:
                num_scenarios = int(request.form.get("num_scenarios", "5").strip())
                num_variants = int(request.form.get("num_variants", "5").strip())
                temperature = float(request.form.get("temperature", "0.7").strip())
            except ValueError:
                return render_template(
                    "index.html",
                    error="Scenario, variant, and temperature values must be numeric.",
                    active_menu=active_menu,
                    selected_template=template,
                )

            num_scenarios = max(1, min(num_scenarios, 50))
            num_variants = max(1, min(num_variants, 25))
            temperature = max(0.0, min(temperature, 1.5))

            sentiments_raw = request.form.get("sentiments", "angry,confused,neutral").strip()
            sentiment_probs_raw = request.form.get("sentiment_probs", "0.15,0.30,0.55").strip()
            speech_raw = request.form.get("user_speech", "casual,professional,slang,typos").strip()
            speech_probs_raw = request.form.get("user_speech_probs", "0.5,0.2,0.1,0.2").strip()
            custom_intents = request.form.get("custom_intents", "").strip()

            sentiments = parse_label_list(sentiments_raw, ["neutral"])
            user_speech = parse_label_list(speech_raw, ["casual"])
            try:
                sentiment_probs = parse_probability_list(sentiment_probs_raw, len(sentiments))
                user_speech_probs = parse_probability_list(speech_probs_raw, len(user_speech))
                generated_file = generate_collections_csv_file(
                    num_scenarios=num_scenarios,
                    num_variants=num_variants,
                    temperature=temperature,
                    sentiments=sentiments,
                    sentiment_probs=sentiment_probs,
                    user_speech=user_speech,
                    user_speech_probs=user_speech_probs,
                    custom_intents=custom_intents,
                )
            except ValueError as error:
                return render_template(
                    "index.html",
                    error=str(error),
                    active_menu=active_menu,
                    selected_template=template,
                    entered_num_scenarios=num_scenarios,
                    entered_num_variants=num_variants,
                    entered_temperature=temperature,
                    entered_sentiments=sentiments_raw,
                    entered_sentiment_probs=sentiment_probs_raw,
                    entered_user_speech=speech_raw,
                    entered_user_speech_probs=speech_probs_raw,
                    entered_custom_intents=custom_intents,
                )

            results = build_results_context(generated_file, source_label="Generated Synthetic Collections CSV")
            return render_template(
                "index.html",
                active_menu=active_menu,
                selected_template=template,
                entered_num_scenarios=num_scenarios,
                entered_num_variants=num_variants,
                entered_temperature=temperature,
                entered_sentiments=sentiments_raw,
                entered_sentiment_probs=sentiment_probs_raw,
                entered_user_speech=speech_raw,
                entered_user_speech_probs=speech_probs_raw,
                entered_custom_intents=custom_intents,
                **results,
            )

        try:
            rows = int(rows_input)
        except ValueError:
            return render_template(
                "index.html",
                error="Rows must be a valid number.",
                active_menu=active_menu,
            )

        try:
            generated_file = generate_csv_file(template=template, rows=rows, custom_columns=custom_columns)
        except ValueError as error:
            return render_template(
                "index.html",
                error=str(error),
                active_menu=active_menu,
            )

        results = build_results_context(generated_file, source_label="Generated CSV")
        return render_template(
            "index.html",
            active_menu=active_menu,
            selected_template=template,
            entered_rows=rows,
            entered_columns=custom_columns,
            **results,
        )

    uploaded_files = request.files.getlist("files")
    saved_files: list[Path] = []
    uploaded_info: list[dict] = []
    base_headers = None
    
    # Create timestamped upload directory
    timestamp_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    session_upload_dir = UPLOAD_DIR / timestamp_str
    session_upload_dir.mkdir(parents=True, exist_ok=True)

    for file in uploaded_files:
        if not file.filename:
            continue
        if not is_allowed_file(file.filename):
            continue

        safe_name = secure_filename(file.filename)
        # We can use safe_name directly now as it is in a unique session folder
        file_path = session_upload_dir / safe_name
        file.save(file_path)
        saved_files.append(file_path)
        
        # Calculate row count and check headers
        df = pd.read_csv(file_path)
        current_headers = list(df.columns)
        
        if base_headers is None:
            base_headers = current_headers
            header_status = "ok"
        else:
            header_status = "ok" if current_headers == base_headers else "mismatch"
            
        uploaded_info.append({
            "name": safe_name, 
            "rows": len(df), 
            "header_status": header_status,
            "headers": current_headers
        })

    if not saved_files:
        return render_template(
            "index.html",
            error="Please upload at least one CSV file.",
            active_menu=active_menu,
        )

    merged_file, report_file = merge_csv_files(saved_files, uploaded_info)
    results = build_results_context(merged_file, source_label="Uploaded & Merged CSV")
    results["uploaded_files"] = uploaded_info
    results["report_filename"] = str(report_file.relative_to(BASE_DIR))

    return render_template(
        "index.html",
        active_menu=active_menu,
        **results,
    )


@app.route("/download/<path:filepath>", methods=["GET"])
def download(filepath: str):
    file_path = BASE_DIR / filepath
    
    # Security: check if file is within ALLOWED directories
    is_safe = False
    for parent in file_path.parents:
        if parent == RESULTS_DIR or parent == OUTPUT_DIR:
            is_safe = True
            break
            
    if not is_safe or not file_path.exists():
        return render_template("index.html", error="File not found or access denied.")
        
    return send_file(file_path, as_attachment=True, download_name=file_path.name)


if __name__ == "__main__":
    app.run(debug=True)
